apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-conf
  labels:
    app: librenms
data:
  config-interfaces-php: |
    <?php
    $config['bad_if_regexp'][] = '/^docker[-\w].*$/';
    $config['bad_if_regexp'][] = '/^lxcbr[0-9]+$/';
    $config['bad_if_regexp'][] = '/^veth.*$/';
    $config['bad_if_regexp'][] = '/^virbr.*$/';
    $config['bad_if_regexp'][] = '/^lo$/';
    $config['bad_if_regexp'][] = '/^macvtap.*$/';
    $config['bad_if_regexp'][] = '/gre.*$/';
    $config['bad_if_regexp'][] = '/tun[0-9]+$/';
  config-influx-php: |
    <?php
    $config['influxdb']['enable'] = true;
    $config['influxdb']['transport'] = 'http'; # Default, other options: https, udp
    $config['influxdb']['host'] = 'influxdb-influxdb';
    $config['influxdb']['port'] = '8086';
    $config['influxdb']['db'] = 'librenms';
    $config['influxdb']['username'] = 'admin';
    $config['influxdb']['password'] = 'admin';
    $config['influxdb']['timeout'] = 0; # Optional
    $config['influxdb']['verifySSL'] = false; # Optional
