apiVersion: v1
kind: Service
metadata:
  name: {{ include "librenms.fullname" . }}
  labels:
    app: {{ include "librenms.name" . }}
    chart: {{ include "librenms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.librenms.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.librenms.service.port }}
      targetPort: 80
      protocol: TCP
      name: librenms-http
  selector:
    app: {{ include "librenms.name" . }}
